<a href="https://colab.research.google.com/github/VictorMagadi/Flame-boss/blob/main/Problem_solving_with_loops_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<div align="center" style=" font-size: 80%; text-align: center; margin: 0 auto">
<img src="https://raw.githubusercontent.com/Explore-AI/Pictures/master/Python-Notebook-Banners/Exercise.png"  style="display: block; margin-left: auto; margin-right: auto;";/>
</div>

# Exercise: Problem solving with loops


This notebook contains more advanced problems in loops. In this notebook, we are given code in a randomised arrangement. We have to rearrange the code to get the desired result.

## Learning objectives

In this train, we will learn how to:
- Solve more complex problems using loops.

## Exercises

### Exercise 1: Ocean cleanup analysis

**Instructions:** Rearrange the code blocks to create a program that calculates the total amount of waste collected in an ocean cleanup campaign over a week. Each day's collection is stored in a list.

In [ ]:
weekly_collection = [340, 220, 455, 300, 385, 520, 410]
total_waste_collected = 0
for daily_collection in weekly_collection:
    total_waste_collected += daily_collection
print(f"Total waste collected over the week: {total_waste_collected} kg")

Rearranged code:

In [2]:
weekly_collection = [340, 220, 455, 300, 385, 520, 410]  # Waste collected
total_waste_collected = 0  # Initialize total

# Loop through collection and add to total
for daily_collection in weekly_collection:
    total_waste_collected += daily_collection

# Print total waste collected
print(f"Total waste collected over the week: {total_waste_collected} kg")


Total waste collected over the week: 2630 kg


Expected result: `Total waste collected over the week: 2630 kg`

### Exercise 2: Endangered species monitoring

**Instructions:** Rearrange the code to create a program that tracks sightings of endangered species over a month, stopping if a certain species is spotted.

In [ ]:
endangered_species = ['Tiger', 'Blue Whale', 'Mountain Gorilla']
sightings = ['Deer', 'Tiger', 'Blue Whale', 'Mountain Gorilla', 'Elephant']
for species in sightings:
if species in endangered_species:
print(f"Endangered species spotted: {species}")
break

Rearranged code:

In [3]:
endangered_species = ['Tiger', 'Blue Whale', 'Mountain Gorilla']
sightings = ['Deer', 'Tiger', 'Blue Whale', 'Mountain Gorilla', 'Elephant']

for species in sightings:
    if species in endangered_species:
        print(f"Endangered species spotted: {species}")
        break


Endangered species spotted: Tiger


Expected result: `Endangered species spotted: Tiger`

### Exercise 3: Forest growth monitoring

**Instructions:** Rearrange the code blocks to create a program that simulates the growth of a forest over years until it reaches a specified threshold area. The forest growth is compounded annually.

In [ ]:
forest_area = 1000 # Initial forest area in square kilometres
growth_rate = 1.05 # 5% annual growth
while forest_area < 1500:
print(f"Forest area after {year} years: {forest_area:.2f} sq km")
forest_area *= growth_rate
year = 0
year += 1

Rearranged code:

In [5]:
# Insert your code here
forest_area = 1000  # Initial forest area in square kilometres
growth_rate = 1.05  # 5% annual growth
year = 0            # Initialize year

while forest_area < 1500:
    print(f"Forest area after {year} years: {forest_area:.2f} sq km")
    forest_area *= growth_rate
    year += 1

# Print
print(f"Forest area after {year} years: {forest_area:.2f} sq km")


Forest area after 0 years: 1000.00 sq km
Forest area after 1 years: 1050.00 sq km
Forest area after 2 years: 1102.50 sq km
Forest area after 3 years: 1157.62 sq km
Forest area after 4 years: 1215.51 sq km
Forest area after 5 years: 1276.28 sq km
Forest area after 6 years: 1340.10 sq km
Forest area after 7 years: 1407.10 sq km
Forest area after 8 years: 1477.46 sq km
Forest area after 9 years: 1551.33 sq km


Expected result:

`Forest area after 1 years: 1050.00 sq km`

`Forest area after 2 years: 1102.50 sq km`

`Forest area after 3 years: 1157.62 sq km`

`Forest area after 4 years: 1215.51 sq km`

`Forest area after 5 years: 1276.28 sq km`

`Forest area after 6 years: 1340.10 sq km`

`Forest area after 7 years: 1407.10 sq km`

`Forest area after 8 years: 1477.46 sq km`

`Forest area after 9 years: 1551.33 sq km`

## Solutions

### Exercise 1: Ocean cleanup analysis

**Explanation:** The program starts by initialising the `weekly_collection` data as a list. We then start at 0, loop through each day and add the day's waste to the total.

In [ ]:
weekly_collection = [340, 220, 455, 300, 385, 520, 410]
total_waste_collected = 0
for daily_collection in weekly_collection:
    total_waste_collected += daily_collection
print(f"Total waste collected over the week: {total_waste_collected} kg")

### Exercise 2: Endangered species monitoring

**Explanation:** The solution begins with two lists: `endangered_species` and `sightings`. The `for` loop iterates through each `species` in `sightings`. If a `species` from `sightings` is found in `endangered_species`, the loop prints the species and exits using break. `Tiger` is the first occurrence of an endangered species, so `if species in endangered_species:` is True, so the `break` statement is executed.

In [ ]:
endangered_species = ['Tiger', 'Blue Whale', 'Mountain Gorilla']
sightings = ['Deer', 'Tiger', 'Blue Whale', 'Mountain Gorilla', 'Elephant']
for species in sightings:
    if species in endangered_species:
        print(f"Endangered species spotted: {species}")
        break

### Exercise 3: Forest growth monitoring

**Explanation:** The program starts by initialising the forest_area to 1000 square kilometres and setting the growth_rate to 5% (1.05). The year variable is initialised to 0 to track the number of years passed. The while loop then iterates, increasing the forest_area by 5% each year, until it reaches or exceeds 1500 square kilometres. After each iteration, the year is incremented by 1 and the current forest area is printed.

In [ ]:
forest_area = 1000 # Initial forest area in square kilometres
growth_rate = 1.05 # 5% annual growth
year = 0
while forest_area < 1500:
    forest_area *= growth_rate
    year += 1
    print(f"Forest area after {year} years: {forest_area:.2f} sq km")

## Summary

This notebook provided a comprehensive exploration of using loops in Python to solve a variety of problems. Through a series of exercises, we gained practical experience with both `for` and `while` loops.

By engaging with these exercises, we not only reinforce our understanding of loop syntax but also start to develop crucial problem-solving skills.

#  

<div align="center" style=" font-size: 80%; text-align: center; margin: 0 auto">
<img src="https://raw.githubusercontent.com/Explore-AI/Pictures/refs/heads/master/ALX_banners/ALX_Navy.png"  style="width:140px";/>
</div>